
2020-08-25 15:45:03
FieldError("Cannot resolve keyword 'a' into field. Choices are: applydeptid, applydeptname, applyerid, applyername, applyremark, applytime, autoid, batchno, caunit, checkamount, checkerid, checkername, checkgist, chkid, chkname, ciid, createtime, expireddate, ittype, labtype, mbatchno, nosub, package, paperno, papertype, producer, remark, reportdeptid, reportdeptname, reporterid, reportername, reporttime, result, samplecount, samplerid, samplername, samplesource, sampletime, sampleunit, seqid, spec, status, warehousemanid, warehousemanname, warrantorid, warrantorname")
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 1863, in add_fields
    join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 1565, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 1481, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'a' into field. Choices are: applydeptid, applydeptname, applyerid, applyername, applyremark, applytime, autoid, batchno, caunit, checkamount, checkerid, checkername, checkgist, chkid, chkname, ciid, createtime, expireddate, ittype, labtype, mbatchno, nosub, package, paperno, papertype, producer, remark, reportdeptid, reportdeptname, reporterid, reportername, reporttime, result, samplecount, samplerid, samplername, samplesource, sampletime, sampleunit, seqid, spec, status, warehousemanid, warehousemanname, warrantorid, warrantorname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pyproject\gmpsystem\labrecord\models\labmodel.py", line 17, in get_labrecord
    return res.values_list(*args, flat=flat)
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\query.py", line 868, in values_list
    clone = self._values(*_fields, **expressions)
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\query.py", line 836, in _values
    clone.query.set_values(fields)
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 2172, in set_values
    self.add_fields(field_names, True)
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 1885, in add_fields
    raise FieldError("Cannot resolve keyword %r into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'a' into field. Choices are: applydeptid, applydeptname, applyerid, applyername, applyremark, applytime, autoid, batchno, caunit, checkamount, checkerid, checkername, checkgist, chkid, chkname, ciid, createtime, expireddate, ittype, labtype, mbatchno, nosub, package, paperno, papertype, producer, remark, reportdeptid, reportdeptname, reporterid, reportername, reporttime, result, samplecount, samplerid, samplername, samplesource, sampletime, sampleunit, seqid, spec, status, warehousemanid, warehousemanname, warrantorid, warrantorname

获取检验记录时出错
a
args=["p", "p", "l", "y", "s", "o", "u", "o", "r", "c", "e"]
kwargs={"chkid": "0304711"}
--------------------
2020-08-25 15:50:11
FieldError("Cannot resolve keyword 'applysouorce' into field. Choices are: applydeptid, applydeptname, applyerid, applyername, applyremark, applytime, autoid, batchno, caunit, checkamount, checkerid, checkername, checkgist, chkid, chkname, ciid, createtime, expireddate, ittype, labtype, mbatchno, nosub, package, paperno, papertype, producer, remark, reportdeptid, reportdeptname, reporterid, reportername, reporttime, result, samplecount, samplerid, samplername, samplesource, sampletime, sampleunit, seqid, spec, status, warehousemanid, warehousemanname, warrantorid, warrantorname")
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 1863, in add_fields
    join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 1565, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 1481, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'applysouorce' into field. Choices are: applydeptid, applydeptname, applyerid, applyername, applyremark, applytime, autoid, batchno, caunit, checkamount, checkerid, checkername, checkgist, chkid, chkname, ciid, createtime, expireddate, ittype, labtype, mbatchno, nosub, package, paperno, papertype, producer, remark, reportdeptid, reportdeptname, reporterid, reportername, reporttime, result, samplecount, samplerid, samplername, samplesource, sampletime, sampleunit, seqid, spec, status, warehousemanid, warehousemanname, warrantorid, warrantorname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pyproject\gmpsystem\labrecord\models\labmodel.py", line 17, in get_labrecord
    return res.values_list(*args, flat=flat)
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\query.py", line 868, in values_list
    clone = self._values(*_fields, **expressions)
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\query.py", line 836, in _values
    clone.query.set_values(fields)
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 2172, in set_values
    self.add_fields(field_names, True)
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 1885, in add_fields
    raise FieldError("Cannot resolve keyword %r into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'applysouorce' into field. Choices are: applydeptid, applydeptname, applyerid, applyername, applyremark, applytime, autoid, batchno, caunit, checkamount, checkerid, checkername, checkgist, chkid, chkname, ciid, createtime, expireddate, ittype, labtype, mbatchno, nosub, package, paperno, papertype, producer, remark, reportdeptid, reportdeptname, reporterid, reportername, reporttime, result, samplecount, samplerid, samplername, samplesource, sampletime, sampleunit, seqid, spec, status, warehousemanid, warehousemanname, warrantorid, warrantorname

获取检验记录时出错
applysouorce
kwargs={"chkid": "0304711"}
--------------------