
2020-10-13 17:14:02
FieldError("Cannot resolve keyword 'stuffkind' into field. Choices are: allowno, autoid, basicamount, basicunit, bpunit, ceffect, checkitems, checkunit, countercheckdays, cstandard, cunit, expireddays, externalno, inputcode, kind, kindinputcode, lowlimit, mpamount, mpunit, package, packagelv, plid, presunit, producer, spamount, spec, spprice, spunit, storage, stuffid, stuffname, stuffsupplyers, stufftype, unit, upperlimit")
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 1863, in add_fields
    join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 1565, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 1481, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'stuffkind' into field. Choices are: allowno, autoid, basicamount, basicunit, bpunit, ceffect, checkitems, checkunit, countercheckdays, cstandard, cunit, expireddays, externalno, inputcode, kind, kindinputcode, lowlimit, mpamount, mpunit, package, packagelv, plid, presunit, producer, spamount, spec, spprice, spunit, storage, stuffid, stuffname, stuffsupplyers, stufftype, unit, upperlimit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pyproject\gmpsystem\stuff\models\stuffmodel.py", line 55, in get_stuffdict
    res = Stuffdictionary.objects.filter(**kwargs).values_list(*args,
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\query.py", line 868, in values_list
    clone = self._values(*_fields, **expressions)
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\query.py", line 836, in _values
    clone.query.set_values(fields)
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 2172, in set_values
    self.add_fields(field_names, True)
  File "D:\Anaconda3\envs\py3.8.5\lib\site-packages\django\db\models\sql\query.py", line 1885, in add_fields
    raise FieldError("Cannot resolve keyword %r into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'stuffkind' into field. Choices are: allowno, autoid, basicamount, basicunit, bpunit, ceffect, checkitems, checkunit, countercheckdays, cstandard, cunit, expireddays, externalno, inputcode, kind, kindinputcode, lowlimit, mpamount, mpunit, package, packagelv, plid, presunit, producer, spamount, spec, spprice, spunit, storage, stuffid, stuffname, stuffsupplyers, stufftype, unit, upperlimit

获取产品物料时出错
cunit
args=["stuffkind", "stufftype", "allowno", "countercheckdays", "spamount"]
kwargs={"stuffid": "05030011"}
--------------------