2020-04-16 16:07:36
TypeError("'ProductModel' object is not iterable")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\product\models\productmodel.py", line 66, in delete_productlabel
    image_list = Productlabel.objects.filter(autoid__in=autoid).values_list("imgid", flag=True)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1116, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\lookups.py", line 204, in get_prep_lookup
    for rhs_value in self.rhs:
TypeError: 'ProductModel' object is not iterable

删除产品标签图时出错
2020-04-16 16:10:24
TypeError("'ProductModel' object is not iterable")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\product\models\productmodel.py", line 66, in delete_productlabel
    image_list = Productlabel.objects.filter(autoid__in=autoid).values_list("imgid", flag=True)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1116, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\lookups.py", line 204, in get_prep_lookup
    for rhs_value in self.rhs:
TypeError: 'ProductModel' object is not iterable

删除产品标签图时出错
2020-04-16 16:10:51
TypeError("'ProductModel' object is not iterable")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\product\models\productmodel.py", line 66, in delete_productlabel
    image_list = Productlabel.objects.filter(autoid__in=autoid).values_list("imgid", flag=True)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1116, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\lookups.py", line 204, in get_prep_lookup
    for rhs_value in self.rhs:
TypeError: 'ProductModel' object is not iterable

删除产品标签图时出错
2020-04-16 16:12:23
TypeError("'ProductModel' object is not iterable")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\product\models\productmodel.py", line 66, in delete_productlabel
    image_list = Productlabel.objects.filter(autoid__in=autoid).values_list("imgid", flag=True)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1116, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\lookups.py", line 204, in get_prep_lookup
    for rhs_value in self.rhs:
TypeError: 'ProductModel' object is not iterable

删除产品标签图时出错
2020-04-16 16:12:43
TypeError("'ProductModel' object is not iterable")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\product\models\productmodel.py", line 66, in delete_productlabel
    image_list = Productlabel.objects.filter(autoid__in=autoid).values_list("imgid", flag=True)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1116, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\lookups.py", line 204, in get_prep_lookup
    for rhs_value in self.rhs:
TypeError: 'ProductModel' object is not iterable

删除产品标签图时出错
2020-04-16 16:24:41
TypeError("values_list() got an unexpected keyword argument 'flag'")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\product\models\productmodel.py", line 66, in delete_productlabel
    image_list = Productlabel.objects.filter(autoid__in=autoid).values_list("imgid", flag=True)
TypeError: values_list() got an unexpected keyword argument 'flag'

删除产品标签图时出错
kwargs={"autoid": ["88"], "args": []}
-------------------------------------------------------2020-04-16 16:25:29
TypeError("values_list() got an unexpected keyword argument 'flag'")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\product\models\productmodel.py", line 66, in delete_productlabel
    image_list = Productlabel.objects.filter(autoid__in=autoid).values_list("imgid", flag=True)
TypeError: values_list() got an unexpected keyword argument 'flag'

删除产品标签图时出错
kwargs={"autoid": ["88"], "args": []}
-------------------------------------------------------2020-04-16 16:26:30
TypeError("values_list() got an unexpected keyword argument 'flag'")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\product\models\productmodel.py", line 66, in delete_productlabel
    image_list = Productlabel.objects.filter(autoid__in=autoid).values_list("imgid", flag=True)
TypeError: values_list() got an unexpected keyword argument 'flag'

删除产品标签图时出错
kwargs={"autoid": ["88"], "args": []}
-------------------------------------------------------2020-04-16 16:27:22
AttributeError("type object 'Imagelib' has no attribute 'filter'")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\product\models\productmodel.py", line 68, in delete_productlabel
    image_model.delete_image(image_list)
  File "d:\pyproject\GMPsystem\imageslib\controllers\image.py", line 14, in delete_image
    return self.IM.delete_image(autoid)
  File "d:\pyproject\GMPsystem\imageslib\models\imagemodel.py", line 14, in delete_image
    return Imagelib.filter(autoid__in=autoid).delete()
AttributeError: type object 'Imagelib' has no attribute 'filter'

删除产品标签图时出错
kwargs={"autoid": ["88"], "args": []}
-------------------------------------------------------2020-04-16 16:28:13
AttributeError("type object 'Productlabel' has no attribute 'filter'")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\product\models\productmodel.py", line 69, in delete_productlabel
    return Productlabel.filter(autoid__in=autoid).delete()
AttributeError: type object 'Productlabel' has no attribute 'filter'

删除产品标签图时出错
kwargs={"autoid": ["88"], "args": []}
-------------------------------------------------------