
2020-05-15 10:30:10
FieldDoesNotExist("Producingplan has no field named 'bpconstitutoriD'")
Traceback (most recent call last):
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\options.py", line 565, in get_field
    return self.fields_map[field_name]
KeyError: 'bpconstitutoriD'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\product\models\productmodel.py", line 158, in update_producingplan
    **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 737, in update
    query.add_update_values(kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\subqueries.py", line 117, in add_update_values
    field = self.get_meta().get_field(name)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\options.py", line 567, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Producingplan has no field named 'bpconstitutoriD'

更新生产指令出错
17
kwargs={"planamount": "1245", "batchno": "2020051501", "instructorid": "001", "instructorname": "sys02", "plantime": "2020-05-15 10:23:13", "deptid": "002", "deptname": "生产部", "bpconstitutoriD": "001", "bpconstitutorname": "sys02", "bpCOnsDate": "2020-05-15"}
-------------------------------------------------------
2020-05-15 11:26:33
FieldDoesNotExist("Producingplan has no field named 'bpconstitutoriD'")
Traceback (most recent call last):
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\options.py", line 565, in get_field
    return self.fields_map[field_name]
KeyError: 'bpconstitutoriD'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\product\models\productmodel.py", line 158, in update_producingplan
    **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 737, in update
    query.add_update_values(kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\subqueries.py", line 117, in add_update_values
    field = self.get_meta().get_field(name)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\options.py", line 567, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Producingplan has no field named 'bpconstitutoriD'

更新生产指令出错
18
kwargs={"planamount": "1234", "batchno": "2020051502", "instructorid": "001", "instructorname": "sys02", "plantime": "2020-05-15 11:26:12", "deptid": "002", "deptname": "生产部", "bpconstitutoriD": "001", "bpconstitutorname": "sys02", "bpCOnsDate": "2020-05-15"}
-------------------------------------------------------