
2020-08-13 14:49:06
FieldError("Cannot resolve keyword 'ppidid' into field. Choices are: allowno, autoid, backamount, backtime, batchno, checkamount, content, cunit, destroyamount, destroydate, destroyerid, destroyername, destroymethod, drawamount, fe, flag, impurity, ismainaux, kind, loss, lpid, lrid, mbatchno, midamount, package, ppid, pracamount, presamount, presunit, price, producer, rdensity, realamount, remark, restamount, sdpid, seqid, spec, srid, stuffid, stuffname, stufftype, supervisorid, supervisorname, unit, water, wdid, wdname")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\stuff\models\stuffmodel.py", line 64, in get_prodstuff
    res = Productstuff.objects.filter(**kwargs).values_list(*args, flat=flat)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1382, in _add_q
    check_filterable=check_filterable,
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1251, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1088, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1484, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'ppidid' into field. Choices are: allowno, autoid, backamount, backtime, batchno, checkamount, content, cunit, destroyamount, destroydate, destroyerid, destroyername, destroymethod, drawamount, fe, flag, impurity, ismainaux, kind, loss, lpid, lrid, mbatchno, midamount, package, ppid, pracamount, presamount, presunit, price, producer, rdensity, realamount, remark, restamount, sdpid, seqid, spec, srid, stuffid, stuffname, stufftype, supervisorid, supervisorname, unit, water, wdid, wdname

获取产品物料时出错
autoid
args=["stuffid", "stuffname", "kind", "spec", "package", "presamount", "pracamount", "drawamount", "content", "water", "impurity", "rdensity"]
kwargs={"ppidid": 36, "version": "03020515"}
--------------------
2020-08-13 14:51:01
FieldError("Cannot resolve keyword 'version' into field. Choices are: allowno, autoid, backamount, backtime, batchno, checkamount, content, cunit, destroyamount, destroydate, destroyerid, destroyername, destroymethod, drawamount, fe, flag, impurity, ismainaux, kind, loss, lpid, lrid, mbatchno, midamount, package, ppid, pracamount, presamount, presunit, price, producer, rdensity, realamount, remark, restamount, sdpid, seqid, spec, srid, stuffid, stuffname, stufftype, supervisorid, supervisorname, unit, water, wdid, wdname")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\stuff\models\stuffmodel.py", line 64, in get_prodstuff
    res = Productstuff.objects.filter(**kwargs).values_list(*args, flat=flat)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1382, in _add_q
    check_filterable=check_filterable,
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1251, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1088, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1484, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'version' into field. Choices are: allowno, autoid, backamount, backtime, batchno, checkamount, content, cunit, destroyamount, destroydate, destroyerid, destroyername, destroymethod, drawamount, fe, flag, impurity, ismainaux, kind, loss, lpid, lrid, mbatchno, midamount, package, ppid, pracamount, presamount, presunit, price, producer, rdensity, realamount, remark, restamount, sdpid, seqid, spec, srid, stuffid, stuffname, stufftype, supervisorid, supervisorname, unit, water, wdid, wdname

获取产品物料时出错
autoid
args=["stuffid", "stuffname", "kind", "spec", "package", "presamount", "pracamount", "drawamount", "content", "water", "impurity", "rdensity"]
kwargs={"ppid": 36, "version": "03020515"}
--------------------
2020-08-13 14:53:47
FieldError("Cannot resolve keyword 'version' into field. Choices are: allowno, autoid, backamount, backtime, batchno, checkamount, content, cunit, destroyamount, destroydate, destroyerid, destroyername, destroymethod, drawamount, fe, flag, impurity, ismainaux, kind, loss, lpid, lrid, mbatchno, midamount, package, ppid, pracamount, presamount, presunit, price, producer, rdensity, realamount, remark, restamount, sdpid, seqid, spec, srid, stuffid, stuffname, stufftype, supervisorid, supervisorname, unit, water, wdid, wdname")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\stuff\models\stuffmodel.py", line 64, in get_prodstuff
    res = Productstuff.objects.filter(**kwargs).values_list(*args, flat=flat)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1382, in _add_q
    check_filterable=check_filterable,
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1251, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1088, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1484, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'version' into field. Choices are: allowno, autoid, backamount, backtime, batchno, checkamount, content, cunit, destroyamount, destroydate, destroyerid, destroyername, destroymethod, drawamount, fe, flag, impurity, ismainaux, kind, loss, lpid, lrid, mbatchno, midamount, package, ppid, pracamount, presamount, presunit, price, producer, rdensity, realamount, remark, restamount, sdpid, seqid, spec, srid, stuffid, stuffname, stufftype, supervisorid, supervisorname, unit, water, wdid, wdname

获取产品物料时出错
autoid
args=["stuffid", "stuffname", "kind", "spec", "package", "presamount", "pracamount", "drawamount", "content", "water", "impurity", "rdensity"]
kwargs={"ppid": 36, "version": "03020515"}
--------------------
2020-08-13 14:56:23
FieldError("Cannot resolve keyword 'version' into field. Choices are: allowno, autoid, backamount, backtime, batchno, checkamount, content, cunit, destroyamount, destroydate, destroyerid, destroyername, destroymethod, drawamount, fe, flag, impurity, ismainaux, kind, loss, lpid, lrid, mbatchno, midamount, package, ppid, pracamount, presamount, presunit, price, producer, rdensity, realamount, remark, restamount, sdpid, seqid, spec, srid, stuffid, stuffname, stufftype, supervisorid, supervisorname, unit, water, wdid, wdname")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\stuff\models\stuffmodel.py", line 64, in get_prodstuff
    res = Productstuff.objects.filter(**kwargs).values_list(*args, flat=flat)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1382, in _add_q
    check_filterable=check_filterable,
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1251, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1088, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1484, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'version' into field. Choices are: allowno, autoid, backamount, backtime, batchno, checkamount, content, cunit, destroyamount, destroydate, destroyerid, destroyername, destroymethod, drawamount, fe, flag, impurity, ismainaux, kind, loss, lpid, lrid, mbatchno, midamount, package, ppid, pracamount, presamount, presunit, price, producer, rdensity, realamount, remark, restamount, sdpid, seqid, spec, srid, stuffid, stuffname, stufftype, supervisorid, supervisorname, unit, water, wdid, wdname

获取产品物料时出错
autoid
args=["stuffid", "stuffname", "kind", "spec", "package", "presamount", "pracamount", "drawamount", "content", "water", "impurity", "rdensity"]
kwargs={"ppid": 36, "version": "03020515"}
--------------------
2020-08-13 14:58:02
FieldError("Cannot resolve keyword 'version' into field. Choices are: allowno, autoid, backamount, backtime, batchno, checkamount, content, cunit, destroyamount, destroydate, destroyerid, destroyername, destroymethod, drawamount, fe, flag, impurity, ismainaux, kind, loss, lpid, lrid, mbatchno, midamount, package, ppid, pracamount, presamount, presunit, price, producer, rdensity, realamount, remark, restamount, sdpid, seqid, spec, srid, stuffid, stuffname, stufftype, supervisorid, supervisorname, unit, water, wdid, wdname")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\stuff\models\stuffmodel.py", line 64, in get_prodstuff
    res = Productstuff.objects.filter(**kwargs).values_list(*args, flat=flat)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1382, in _add_q
    check_filterable=check_filterable,
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1251, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1088, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1484, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'version' into field. Choices are: allowno, autoid, backamount, backtime, batchno, checkamount, content, cunit, destroyamount, destroydate, destroyerid, destroyername, destroymethod, drawamount, fe, flag, impurity, ismainaux, kind, loss, lpid, lrid, mbatchno, midamount, package, ppid, pracamount, presamount, presunit, price, producer, rdensity, realamount, remark, restamount, sdpid, seqid, spec, srid, stuffid, stuffname, stufftype, supervisorid, supervisorname, unit, water, wdid, wdname

获取产品物料时出错
autoid
args=["stuffid", "stuffname", "kind", "spec", "package", "presamount", "pracamount", "drawamount", "content", "water", "impurity", "rdensity"]
kwargs={"ppid": 36, "version": "03020515"}
--------------------
2020-08-13 14:59:37
FieldError("Cannot resolve keyword 'version' into field. Choices are: allowno, autoid, backamount, backtime, batchno, checkamount, content, cunit, destroyamount, destroydate, destroyerid, destroyername, destroymethod, drawamount, fe, flag, impurity, ismainaux, kind, loss, lpid, lrid, mbatchno, midamount, package, ppid, pracamount, presamount, presunit, price, producer, rdensity, realamount, remark, restamount, sdpid, seqid, spec, srid, stuffid, stuffname, stufftype, supervisorid, supervisorname, unit, water, wdid, wdname")
Traceback (most recent call last):
  File "d:\pyproject\GMPsystem\stuff\models\stuffmodel.py", line 64, in get_prodstuff
    res = Productstuff.objects.filter(**kwargs).values_list(*args, flat=flat)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1382, in _add_q
    check_filterable=check_filterable,
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1251, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1088, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Anaconda3\envs\lib\site-packages\django\db\models\sql\query.py", line 1484, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'version' into field. Choices are: allowno, autoid, backamount, backtime, batchno, checkamount, content, cunit, destroyamount, destroydate, destroyerid, destroyername, destroymethod, drawamount, fe, flag, impurity, ismainaux, kind, loss, lpid, lrid, mbatchno, midamount, package, ppid, pracamount, presamount, presunit, price, producer, rdensity, realamount, remark, restamount, sdpid, seqid, spec, srid, stuffid, stuffname, stufftype, supervisorid, supervisorname, unit, water, wdid, wdname

获取产品物料时出错
autoid
args=["stuffid", "stuffname", "kind", "spec", "package", "presamount", "pracamount", "drawamount", "content", "water", "impurity", "rdensity"]
kwargs={"ppid": 36, "version": "03020515"}
--------------------